[package]
name = "knox_codegen_wasm"
version = "0.1.0"
edition = "2021"
description = "Wasm emitter and codegen for Knox"

[dependencies]
knox_syntax = { path = "../knox_syntax" }
wasm-encoder = "0.21"
